# Generated by Django 5.1.3 on 2024-11-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='batch_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
