# Generated by Django 5.1.3 on 2024-11-20 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement_APP', '0004_alter_stocklog_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocklog',
            old_name='version',
            new_name='product_version',
        ),
    ]
