# Generated by Django 5.1.3 on 2024-11-24 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0001_initial'),
        ('ProductManagement_APP', '0005_rename_version_stocklog_product_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitem',
            name='product',
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='product_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProductManagement_APP.productversion'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
