# Generated by Django 5.1.2 on 2024-10-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventoryManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reorder_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
