# Generated by Django 5.1.3 on 2024-12-01 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Debt_Management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
